general:
    path: http://www.example.com                        # The url that your blog will be visible
    timezone: Europe/Paris                              # See http://php.net/manual/en/timezones.php

article:
    input: _data/(name)                                 # The path of the article (name) = article name
    layouts: _layouts/default/(layout).html.tpl         # The path of the layout    (layout) = article layout
    output: output/articles/(name)                      # The path to be written to (name) = article name