general:
	path: http://www.example.com                        # The url that your blog will be visible
	timezone: Europe/Paris                              # See http://php.net/manual/en/timezones.php
	logging: iceberg.log                                # Where Iceberg should log errors. Set to false for none

article:
	input: data/(name)                                 	# The path of the article (name) = article name
	layouts: layouts/default/(layout).html.tpl         	# The path of the layout (layout) = article layout
	output: output/articles/(name)                      # The path to be written to (name) = article name
	delimiter: -----									# The metadata delimiter at the top of your markdown files